[build-system]
requires = ["setuptools>=77.0"]
build-backend = "setuptools.build_meta"

[project]
name = "evdev"
version = "1.9.3"
description = "Bindings to the Linux input handling subsystem"
keywords = ["evdev", "input", "uinput"]
readme = "README.md"
license = "BSD-3-Clause"
requires-python = ">=3.11"
authors = [
  { name="Georgi Valkov", email="georgi.t.valkov@gmail.com" },
]
maintainers = [
  { name="Tobi", email="proxima@sezanzeb.de" },
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX :: Linux",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries",
    "Programming Language :: Python :: Implementation :: CPython",
]

[project.urls]
"Homepage" = "https://github.com/gvalkov/python-evdev"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
ignore = ["E265", "E241", "F403", "F401", "E401", "E731"]

[tool.pylint.'MESSAGES CONTROL']
disable = """
    no-member,
"""

[tool.pylint.typecheck]
generated-members = ["evdev.ecodes.*"]
ignored-modules= ["evdev._*"]

[dependency-groups]
dev = [
    "build>=1.5.0",
    "cibuildwheel>=2.23.4",
    "furo>=2025.12.19",
    "pytest>=9.1.1",
    "ruff>=0.16.4",
    "setuptools>=82.0.1",
    "sphinx>=9.0.4",
    "sphinx-autobuild>=2025.8.25",
    "sphinx-autodoc-typehints>=2.3.0",
    "sphinx-copybutton>=0.5.2",
    "twine>=7.0.0",
]
