name: Test install

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v7
      - name: Set up uv
        uses: astral-sh/setup-uv@v10

      - name: Install python-evdev
        run: |
          uv venv -p ${{ matrix.python-version }}
          uv pip install -v .
          (cd /tmp && "$GITHUB_WORKSPACE/.venv/bin/python" -c "import evdev.ecodes; print(evdev.ecodes)")
