name: Lint

on:
  - push
  - pull_request

jobs:
  pylint:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.14"]

    steps:
      - uses: actions/checkout@v7
      - name: Set up uv
        uses: astral-sh/setup-uv@v10
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check for pylint errors
        run: |
          uv venv
          uv pip install pylint setuptools
          uv run python setup.py build
          uv run pylint --verbose -E build/lib*/evdev
