name: Test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11", "3.14"]

    steps:
      - uses: actions/checkout@v7
      - name: Set up uv
        uses: astral-sh/setup-uv@v10
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run pytest tests
        # sudo required to write to uinputs
        run: |
          sudo uv venv
          sudo uv pip install -e . pytest
          sudo uv run pytest tests
